In [1]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv('data.csv', delimiter=',', names=['name','handi','water','adop','physician','el','reli','anti',
                                                'aid','mx','immigration','syn','education','superfund','crime','duty','duty','export'])

/home/akash/.local/lib/python3.5/site-packages/pandas/io/parsers.py:678: UserWarning: Duplicate names specified. This will raise an error in the future.
  return _read(filepath_or_buffer, kwds)

In [17]:
df1 = df.apply(lambda x: pd.factorize(x)[0])
df1.head(10)

,name,handi,water,adop,physician,el,reli,anti,aid,mx,immigration,syn,education,superfund,crime,duty,duty.1,export
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1
1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,-1
2,1,1,0,1,1,0,0,0,0,0,1,2,1,0,0,0,2,-1
3,1,0,0,1,2,1,0,0,0,0,1,2,1,0,1,0,0,-1
4,1,2,0,1,2,0,0,0,0,0,1,2,2,0,0,1,0,-1
5,1,0,0,1,2,0,0,0,0,0,1,1,1,0,0,1,0,-1
6,1,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1,0,-1
7,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,2,0,-1
8,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,-1
9,1,2,0,1,2,2,1,1,1,1,1,1,1,2,1,2,1,-1

In [21]:
x = df1.iloc[:,1:]
y = df1['name']

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [34]:
#For Decision Tree
from sklearn import tree
from sklearn.neural_network import MLPClassifier

In [35]:
def classify_all():
    clf = tree.DecisionTreeClassifier()
    print(clf.fit(X_train,y_train))
    print(clf.score(X_test,y_test))
    clf = MLPClassifier(solver='lbfgs', alpha=1e-5, 
                        hidden_layer_sizes=(5, 2), random_state=1)
    print(clf.fit(X_train,y_train))
    print(clf.score(X_test,y_test))

In [36]:
classify_all()

NameError: name 'pr' is not defined